
name: ci.yml

#The on section specifies that the workflow should trigger on push events to the master or main branch.
on:
  push:
    branches:
      - master
      - main
      - issue/*'

#The jobs section defines a single job called mainline, which runs on the ubuntu-latest operating system.      
jobs:

  mainline:
    runs-on: ubuntu-latest
    steps:
    #The steps section of the mainline job specifies two steps:
    #The first step checks out the repository code using the actions/checkout action.
      - name: Checkout code
        uses: actions/checkout@v2
        #The second step runs a placeholder Build and test command that you will need to replace with your own build and test commands.
      - name: Build and test
        run: |
          # Add build and test commands here

   verify_issue:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/issue/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get issue details
        id: issue
        uses: peter-evans/get-issue-details@v1
        with:
          issue-number: ${{ github.event.pull_request.number }}
      - name: Print issue details
        run: |
          echo "Issue Title: ${{ steps.issue.outputs.title }}"
          echo "Issue Body: ${{ steps.issue.outputs.body }}"
          echo "Issue Number: ${{ steps.issue.outputs.number }}"



      