name: verify-issue.yml

on:
  push:
    branches:
      - 'issue/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and test
        run: gh issue comment $ISSUE --body "Issue is now verified"
        
      